# Minimal Jekyll config (GitHub Pages will auto-build; this site works even without Jekyll)
title: Health Informatics Lab · Temple University
description: AI, data science, and health equity
theme: null